### ISSUE TITLE
boom

### ISSUE THREAD

**Issue by ShuBo6** [golang-infrastructure/go-if-expression#5]
```go

func TestMap(t *testing.T) {
	m := map[string]interface{}{
		"foo": "bar",
	}
	t.Log(m["bad"])    // nil
	t.Log(if_expression.Return(m["bad"] != nil, m["bad"].(string), "")) // ⚠️ 范型传nil进来就panic了.
}

```

**Comment by CC11001100** [comment]
这么尴尬的嘛，稍等树哥我康康。。。

**Comment by CC11001100** [comment]
> 

是因为`m["bad"].(string)`处的`m["bad"]`没有取到值？所以在试图将nil强转为string的时候panic了？

**Comment by CC11001100** [comment]
如果不进行类型强转，直接传递：
```go
func TestMap(t *testing.T) {
	m := map[string]interface{}{
		"foo": "bar",
	}
	//t.Log(m["bad"])    // nil
	t.Log(Return(m["bad"] != nil, m["bad"], ""))
}
```

这样似乎是可以的

**Comment by ShuBo6** [comment]
> 

```go
// 这里t不能为nil，可能需要反射判断下空指针。我一开始也很费解为啥panic。。他妈的还是理解不到位
func Return[T any](boolExpression bool, trueReturnValue, falseReturnValue T) T {
	if boolExpression {
		return trueReturnValue
	} else {
		return falseReturnValue
	}
}
```

**Comment by ShuBo6** [comment]
> 

确实

**Comment by ShuBo6** [comment]
> 

不好意思我的锅

**Comment by CC11001100** [comment]
> > 
> 
> 不好意思我的锅

啊哈哈哈没关系互相讨论交流，愿意提出建议就很感谢啦，谢谢树哥支持，改天请你喝冰阔乐！

**Comment by ShuBo6** [comment]
> > > 
> > 
> > 
> > 不好意思我的锅
> 
> 啊哈哈哈没关系互相讨论交流，愿意提出建议就很感谢啦，谢谢树哥支持，改天请你喝冰阔乐！

二爷yyds

**Comment by CC11001100** [comment]
> > > > 
> > > 
> > > 
> > > 不好意思我的锅
> > 
> > 
> > 啊哈哈哈没关系互相讨论交流，愿意提出建议就很感谢啦，谢谢树哥支持，改天请你喝冰阔乐！
> 
> 二爷yyds

树哥yyds, too！

**Comment by songzhibin97** [comment]
这个就是这样，入参进去的时候如果是nil.xxx肯定会panic的，没什么好办法可以避免

**Comment by songzhibin97** [comment]
> 这个就是这样，入参进去的时候如果是nil.xxx肯定会panic的，没什么好办法可以避免

如果传一个函数的话，利用闭包可以避免 f1()x f2()x if bool {return f1()} else {return f2()} 好像有点啰嗦？

**Comment by CC11001100** [comment]
> 似乎是因为经过了参数传递，泛型具有了对应类型的默认值，如果是在泛型参数里面返回T的话需要：
> 
> ```go
> var zero T 
> return zero 
> ```
> 
> 使其具有T类型的默认值，具体原因好像是跟泛型实现原理有关不好意思这块儿我也不大清楚，就是看到别人这么用就学了。。。

对不起我刚才说错了，我又细看了下，刚才是因为这个T的类型实际上是any，所以传递interface{} nil进去的时候没问题，如果换成明确的类型，则编译无法通过：
```go
func TestMap(t *testing.T) {
	m := map[string]interface{}{
		"foo": "bar",
	}
	m["bar"] = "aaa"
	//t.Log(m["bad"])    // nil
	var v string
	v = Return[string](m["bad"] == nil, m["bar"], "aaa")  //  m["bar"]的类型不对
	t.Log(v)
}
```

**Comment by songzhibin97** [comment]
> > 似乎是因为经过了参数传递，泛型具有了对应类型的默认值，如果是在泛型参数里面返回T的话需要：
> > ```go
> > var zero T 
> > return zero 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 使其具有T类型的默认值，具体原因好像是跟泛型实现原理有关不好意思这块儿我也不大清楚，就是看到别人这么用就学了。。。
> 
> 对不起我刚才说错了，我又细看了下，刚才是因为这个T的类型实际上是any，所以传递interface{} nil进去的时候没问题，如果换成明确的类型，则编译无法通过：
> 
> ```go
> func TestMap(t *testing.T) {
> 	m := map[string]interface{}{
> 		"foo": "bar",
> 	}
> 	m["bar"] = "aaa"
> 	//t.Log(m["bad"])    // nil
> 	var v string
> 	v = Return[string](m["bad"] == nil, m["bar"], "aaa")  //  m["bar"]的类型不对
> 	t.Log(v)
> }
> ```

应该传interface{}进去 Return[interface{}]

**Comment by CC11001100** [comment]
> > 这个就是这样，入参进去的时候如果是nil.xxx肯定会panic的，没什么好办法可以避免
> 
> 如果传一个函数的话，利用闭包可以避免 f1()x f2()x if bool {return f1()} else {return f2()} 好像有点啰嗦？

关于这个安全的类型转换，可以使用我的另一个库：
```
https://github.com/golang-infrastructure/go-cast-anything
```
比如一个可能的用法：
```go 
func TestMap(t *testing.T) {
	m := map[string]interface{}{
		"foo": "bar",
	}
	m["bar"] = "aaa"
	//t.Log(m["bad"])    // nil
	var v string
	v = cast_anything.ToString(Return(m["bad"] == nil, m["bar"], "aaa")) 
	t.Log(v)
}
```
即让if表达式返回随便什么类型，然后再把它修正，虽然这是一个可能性，但是这样子的话感觉就更啰嗦了。。。

**Comment by songzhibin97** [comment]
> > > 这个就是这样，入参进去的时候如果是nil.xxx肯定会panic的，没什么好办法可以避免
> > 
> > 
> > 如果传一个函数的话，利用闭包可以避免 f1()x f2()x if bool {return f1()} else {return f2()} 好像有点啰嗦？
> 
> 关于这个安全的类型转换，可以使用我的另一个库：
> 
> ```
> https://github.com/golang-infrastructure/go-cast-anything
> ```
> 
> 比如一个可能的用法：
> 
> ```go
> func TestMap(t *testing.T) {
> 	m := map[string]interface{}{
> 		"foo": "bar",
> 	}
> 	m["bar"] = "aaa"
> 	//t.Log(m["bad"])    // nil
> 	var v string
> 	v = cast_anything.ToString(Return(m["bad"] == nil, m["bar"], "aaa")) 
> 	t.Log(v)
> }
> ```
> 
> 即让if表达式返回随便什么类型，然后再把它修正，虽然这是一个可能性，但是这样子的话感觉就更啰嗦了。。。

感觉不是一个好的方法。。上述的问题是 panic是因为 nil.(string) 这一步吧，因为结果是已经确定的 而不是 bool再去执行的

**Comment by CC11001100** [comment]
> > > 似乎是因为经过了参数传递，泛型具有了对应类型的默认值，如果是在泛型参数里面返回T的话需要：
> > > ```go
> > > var zero T 
> > > return zero 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 使其具有T类型的默认值，具体原因好像是跟泛型实现原理有关不好意思这块儿我也不大清楚，就是看到别人这么用就学了。。。
> > 
> > 
> > 对不起我刚才说错了，我又细看了下，刚才是因为这个T的类型实际上是any，所以传递interface{} nil进去的时候没问题，如果换成明确的类型，则编译无法通过：
> > ```go
> > func TestMap(t *testing.T) {
> > 	m := map[string]interface{}{
> > 		"foo": "bar",
> > 	}
> > 	m["bar"] = "aaa"
> > 	//t.Log(m["bad"])    // nil
> > 	var v string
> > 	v = Return[string](m["bad"] == nil, m["bar"], "aaa")  //  m["bar"]的类型不对
> > 	t.Log(v)
> > }
> > ```
> 
> 应该传interface{}进去 Return[interface{}]

这样子的话就是对返回值进行强制类型转换，在参数上强转还是在返回值上强转没啥区别，本质问题没有解决。、。、

**Comment by songzhibin97** [comment]
> > > 这个就是这样，入参进去的时候如果是nil.xxx肯定会panic的，没什么好办法可以避免
> > 
> > 
> > 如果传一个函数的话，利用闭包可以避免 f1()x f2()x if bool {return f1()} else {return f2()} 好像有点啰嗦？
> 
> 关于这个安全的类型转换，可以使用我的另一个库：
> 
> ```
> https://github.com/golang-infrastructure/go-cast-anything
> ```
> 
> 比如一个可能的用法：
> 
> ```go
> func TestMap(t *testing.T) {
> 	m := map[string]interface{}{
> 		"foo": "bar",
> 	}
> 	m["bar"] = "aaa"
> 	//t.Log(m["bad"])    // nil
> 	var v string
> 	v = cast_anything.ToString(Return(m["bad"] == nil, m["bar"], "aaa")) 
> 	t.Log(v)
> }
> ```
> 
> 即让if表达式返回随便什么类型，然后再把它修正，虽然这是一个可能性，但是这样子的话感觉就更啰嗦了。。。

例如
```go
type t struct {a string}
func TestMap(t *testing.T) {
	m := map[string]*t{
		"foo": &t{"xx"},
	}
	m["bar"] = "aaa"
	//t.Log(m["bad"])    // nil
	v = Return[string](m["bad"] == nil, m["bar"].a, "aaa") // panic m["bar"].a
}
```

**Comment by CC11001100** [comment]
> > > > 这个就是这样，入参进去的时候如果是nil.xxx肯定会panic的，没什么好办法可以避免
> > > 
> > > 
> > > 如果传一个函数的话，利用闭包可以避免 f1()x f2()x if bool {return f1()} else {return f2()} 好像有点啰嗦？
> > 
> > 
> > 关于这个安全的类型转换，可以使用我的另一个库：
> > ```
> > https://github.com/golang-infrastructure/go-cast-anything
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 比如一个可能的用法：
> > ```go
> > func TestMap(t *testing.T) {
> > 	m := map[string]interface{}{
> > 		"foo": "bar",
> > 	}
> > 	m["bar"] = "aaa"
> > 	//t.Log(m["bad"])    // nil
> > 	var v string
> > 	v = cast_anything.ToString(Return(m["bad"] == nil, m["bar"], "aaa")) 
> > 	t.Log(v)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 即让if表达式返回随便什么类型，然后再把它修正，虽然这是一个可能性，但是这样子的话感觉就更啰嗦了。。。
> 
> 感觉不是一个好的方法。。上述的问题是 panic是因为 nil.(string) 这一步吧，因为结果是已经确定的 而不是 bool再去执行的

我在想也许我应该把参数的泛型约束去掉，允许参数为any，而只把return结果进行转换为对应的类型T？但是我担心这样可能会造成意料之外的值转换

**Comment by CC11001100** [comment]
> > > > > 这个就是这样，入参进去的时候如果是nil.xxx肯定会panic的，没什么好办法可以避免
> > > > 
> > > > 
> > > > 如果传一个函数的话，利用闭包可以避免 f1()x f2()x if bool {return f1()} else {return f2()} 好像有点啰嗦？
> > > 
> > > 
> > > 关于这个安全的类型转换，可以使用我的另一个库：
> > > ```
> > > https://github.com/golang-infrastructure/go-cast-anything
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 比如一个可能的用法：
> > > ```go
> > > func TestMap(t *testing.T) {
> > > 	m := map[string]interface{}{
> > > 		"foo": "bar",
> > > 	}
> > > 	m["bar"] = "aaa"
> > > 	//t.Log(m["bad"])    // nil
> > > 	var v string
> > > 	v = cast_anything.ToString(Return(m["bad"] == nil, m["bar"], "aaa")) 
> > > 	t.Log(v)
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 即让if表达式返回随便什么类型，然后再把它修正，虽然这是一个可能性，但是这样子的话感觉就更啰嗦了。。。
> > 
> > 
> > 感觉不是一个好的方法。。上述的问题是 panic是因为 nil.(string) 这一步吧，因为结果是已经确定的 而不是 bool再去执行的
> 
> 我在想也许我应该把参数的泛型约束去掉，允许参数为any，而只把return结果进行转换为对应的类型T？但是我担心这样可能会造成意料之外的值转换

基于cast_anything可以很简单的实现这个效果，当然前提是那个库要开发完善。。。

**Comment by songzhibin97** [comment]
> > > > 似乎是因为经过了参数传递，泛型具有了对应类型的默认值，如果是在泛型参数里面返回T的话需要：
> > > > ```go
> > > > var zero T 
> > > > return zero 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 使其具有T类型的默认值，具体原因好像是跟泛型实现原理有关不好意思这块儿我也不大清楚，就是看到别人这么用就学了。。。
> > > 
> > > 
> > > 对不起我刚才说错了，我又细看了下，刚才是因为这个T的类型实际上是any，所以传递interface{} nil进去的时候没问题，如果换成明确的类型，则编译无法通过：
> > > ```go
> > > func TestMap(t *testing.T) {
> > > 	m := map[string]interface{}{
> > > 		"foo": "bar",
> > > 	}
> > > 	m["bar"] = "aaa"
> > > 	//t.Log(m["bad"])    // nil
> > > 	var v string
> > > 	v = Return[string](m["bad"] == nil, m["bar"], "aaa")  //  m["bar"]的类型不对
> > > 	t.Log(v)
> > > }
> > > ```
> > 
> > 
> > 应该传interface{}进去 Return[interface{}]
> 
> 这样子的话就是对返回值进行强制类型转换，在参数上强转还是在返回值上强转没啥区别，本质问题没有解决。、。、

本质上上面的map value你是未知的。所以直接套上泛型你没有办法确定V

**Comment by CC11001100** [comment]
> > > > 这个就是这样，入参进去的时候如果是nil.xxx肯定会panic的，没什么好办法可以避免
> > > 
> > > 
> > > 如果传一个函数的话，利用闭包可以避免 f1()x f2()x if bool {return f1()} else {return f2()} 好像有点啰嗦？
> > 
> > 
> > 关于这个安全的类型转换，可以使用我的另一个库：
> > ```
> > https://github.com/golang-infrastructure/go-cast-anything
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 比如一个可能的用法：
> > ```go
> > func TestMap(t *testing.T) {
> > 	m := map[string]interface{}{
> > 		"foo": "bar",
> > 	}
> > 	m["bar"] = "aaa"
> > 	//t.Log(m["bad"])    // nil
> > 	var v string
> > 	v = cast_anything.ToString(Return(m["bad"] == nil, m["bar"], "aaa")) 
> > 	t.Log(v)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 即让if表达式返回随便什么类型，然后再把它修正，虽然这是一个可能性，但是这样子的话感觉就更啰嗦了。。。
> 
> 例如
> 
> ```go
> type t struct {a string}
> func TestMap(t *testing.T) {
> 	m := map[string]*t{
> 		"foo": &t{"xx"},
> 	}
> 	m["bar"] = "aaa"
> 	//t.Log(m["bad"])    // nil
> 	v = Return[string](m["bad"] == nil, m["bar"].a, "aaa") // panic m["bar"].a
> }
> ```

![image](https://user-images.githubusercontent.com/12819457/203718918-4d2d2d64-9d1a-442f-b582-2bfab54c94d6.png)

**Comment by songzhibin97** [comment]
> > > > > 这个就是这样，入参进去的时候如果是nil.xxx肯定会panic的，没什么好办法可以避免
> > > > 
> > > > 
> > > > 如果传一个函数的话，利用闭包可以避免 f1()x f2()x if bool {return f1()} else {return f2()} 好像有点啰嗦？
> > > 
> > > 
> > > 关于这个安全的类型转换，可以使用我的另一个库：
> > > ```
> > > https://github.com/golang-infrastructure/go-cast-anything
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 比如一个可能的用法：
> > > ```go
> > > func TestMap(t *testing.T) {
> > > 	m := map[string]interface{}{
> > > 		"foo": "bar",
> > > 	}
> > > 	m["bar"] = "aaa"
> > > 	//t.Log(m["bad"])    // nil
> > > 	var v string
> > > 	v = cast_anything.ToString(Return(m["bad"] == nil, m["bar"], "aaa")) 
> > > 	t.Log(v)
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 即让if表达式返回随便什么类型，然后再把它修正，虽然这是一个可能性，但是这样子的话感觉就更啰嗦了。。。
> > 
> > 
> > 例如
> > ```go
> > type t struct {a string}
> > func TestMap(t *testing.T) {
> > 	m := map[string]*t{
> > 		"foo": &t{"xx"},
> > 	}
> > 	//t.Log(m["bad"])    // nil
> > 	v = Return[string](m["bad"] == nil, m["bar"].a, "aaa") // panic m["bar"].a
> > }
> > ```
> 
> 想表达的意思是。。。？ ![image](https://user-images.githubusercontent.com/12819457/203718918-4d2d2d64-9d1a-442f-b582-2bfab54c94d6.png)

up了一下

**Comment by songzhibin97** [comment]
> ```go
> type t struct {a string}
> func TestMap(t *testing.T) {
> 	m := map[string]*t{
> 		"foo": &t{"xx"},
> 	}
> 	//t.Log(m["bad"])    // nil
> 	v = Return[string](m["bad"] == nil, m["bar"].a, "aaa") // panic m["bar"].a
> }
> ```

<img width="801" alt="image" src="https://user-images.githubusercontent.com/49082129/203720073-c03cb772-e414-4096-97e6-405bd1ec08e1.png">
```go
type tp struct{ a string }

func TestMap(t *testing.T) {
	m := map[string]*tp{
		"foo": &tp{"xx"},
	}
	//t.Log(m["bad"])    // nil
	v := Return[string](m["bad"] == nil, m["bar"].a, "aaa") // panic m["bar"].a
}

```

**Comment by songzhibin97** [comment]
```go

type tp struct{ a string }

func TestMap(t *testing.T) {
	m := map[string]*tp{
		"foo": &tp{"xx"},
	}
	//t.Log(m["bad"])    // nil
	v := Return[func() string](m["bad"] != nil, func() string { return m["bar"].a }, func() string { return "aaa" }
	t.Log(v()) // "aaa"
}

```

**Comment by CC11001100** [comment]
> > ```go
> > type t struct {a string}
> > func TestMap(t *testing.T) {
> > 	m := map[string]*t{
> > 		"foo": &t{"xx"},
> > 	}
> > 	//t.Log(m["bad"])    // nil
> > 	v = Return[string](m["bad"] == nil, m["bar"].a, "aaa") // panic m["bar"].a
> > }
> > ```
> 
> <img alt="image" width="801" src="https://user-images.githubusercontent.com/49082129/203720073-c03cb772-e414-4096-97e6-405bd1ec08e1.png">
> 
> ```go
> type tp struct{ a string }
> 
> func TestMap(t *testing.T) {
> 	m := map[string]*tp{
> 		"foo": &tp{"xx"},
> 	}
> 	//t.Log(m["bad"])    // nil
> 	v := Return[string](m["bad"] == nil, m["bar"].a, "aaa") // panic m["bar"].a
> }
> ```

这其实是一个新的问题了，超出了这个库要解决的问题，这个例子的问题是链式访问时的空指针问题，有些语言比如node，kotlin等增加了个?用来对链式进行短路避免空指针，而有些语言比如Java引入了Optional，但是Optional对于这种问题也不是很合适，除非语言的语法上引入语法糖，不然仅凭外部库很难解决好这个问题，主要还是此问题所处的代码粒度太细了，太细的粒度稍微一个函数调用都会对可读性产生非常大的影响

**Comment by CC11001100** [comment]
> ```go
> type tp struct{ a string }
> 
> func TestMap(t *testing.T) {
> 	m := map[string]*tp{
> 		"foo": &tp{"xx"},
> 	}
> 	//t.Log(m["bad"])    // nil
> 	v := Return[func() string](m["bad"] != nil, func() string { return m["bar"].a }, func() string { return "aaa" }
> 	t.Log(v()) // "aaa"
> }
> ```

这个库的本意是在不牺牲太多代码可读性的情况下尽可能让代码清爽一些读起来不太累，这个方案是不是有点违背初衷把事情变得更复杂了？

**Comment by songzhibin97** [comment]
是的 注明一下吧 使用这样的外部库很容易就直接使用可能为nil的变量了,可能写if else 这样的逻辑块不会出错,使用这种方便的反而panic了

**Comment by CC11001100** [comment]
> 是的 注明一下吧 使用这样的外部库很容易就直接使用可能为nil的变量了,可能写if else 这样的逻辑块不会出错,使用这种方便的反而panic了

1. 类型强转可能会引起panic，这是个基础的编程习惯问题我无能为力也不应该是这个库的责任，也许应该引入一些linter之类的对代码做静态检查，就像有些coder习惯把err全部_忽略，这必然会导致程序不够健壮； 你在任何使用进行类型强转都需要自己思考是否会panic，就像你在任何时候忽略错误都需要自己思考是否会导致panic一样
2. 而泛型类型不对会被Go的编译器所阻止无法通过编译
3. 我所能做的只是把参数中的泛型干掉，底层加入cast_anything使使用体验更好一些

**Comment by CC11001100** [comment]
> > 是的 注明一下吧 使用这样的外部库很容易就直接使用可能为nil的变量了,可能写if else 这样的逻辑块不会出错,使用这种方便的反而panic了
> 
> 1. 类型强转可能会引起panic，这是个基础的编程习惯问题我无能为力也不应该是这个库的责任，也许应该引入一些linter之类的对代码做静态检查，就像有些coder习惯把err全部_忽略，这必然会导致程序不够健壮； 你在任何使用进行类型强转都需要自己思考是否会panic，就像你在任何时候忽略错误都需要自己思考是否会导致panic一样
> 2. 而泛型类型不对会被Go的编译器所阻止无法通过编译
> 3. 我所能做的只是把参数中的泛型干掉，底层加入cast_anything使使用体验更好一些

关于第三点，一个可能的新的函数签名大概是这样：
```go
func ReturnWithCast[T any](boolExpression bool, any, falseReturnValue any) T 
```
因为在大多数情况类型都会是明确的，参数应该有泛型，而在少数特殊情况下则为其提供可选的自动类型转换，你的想法呢？

**Comment by songzhibin97** [comment]
> ```go
> ```go
> ReturnWithCast[T any](boolExpression bool, trueReturnValue, falseReturnValue any) T
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

```go
// ReturnWithCast[T any](boolExpression bool, trueReturnValue, falseReturnValue any) T // default
// ReturnWithCast[T any](boolExpression bool, trueReturnValue, falseReturnValue any, converter(v interface) T) T 
```
是不是会更好一点呢
